### トップページ
GET http://localhost:3000/

### 記事の一覧
GET http://localhost:3000/posts/

### 記事の詳細ページ
GET http://localhost:3000/posts/1

### 記事の詳細ページ エラー
GET http://localhost:3000/posts/999999

### 記事の詳細ページ エラー
GET http://localhost:3000/posts/acg1

### 記事の詳細ページ エラー
GET http://localhost:3000/posts/1.0


### 記事の削除
DELETE http://localhost:3000/posts/9

### 記事の削除 エラー
DELETE http://localhost:3000/posts/4n

### 記事の削除 エラー
DELETE http://localhost:3000/posts/dfdfdfdfd

### 記事の作成
POST http://localhost:3000/posts/
Content-Type: application/json

{
  "slug": "vdfdfddfdfvddd",
  "title": "タイトルですrerererere",
  "body": "本文です",
  "published": 0,
}

### 記事の編集
PUT http://localhost:3000/posts/10
Content-Type: application/json

{
  "slug": "23255",
  "title": "m",
  "body": "本文です",
  "published": 1
}

### 記事の編集 エラー
PUT http://localhost:3000/posts/10
Content-Type: application/json

{
  "slug": 222,
  "title": "タイトルですrerererere",
  "body": "本文です",
  "published": 1
}
